src/Controller.php

move View to yii\web\Controller

move View to yii\web\Controller

---

tests/filters/auth/AuthMethodTest.php

Fixed "AuthMethodTest"
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | yes
| Tests pass?   | yes

Fixed "AuthMethodTest"

---

tests/session/SessionTest.php

| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

Fix SessionTest

---

composer.lock
src/MultipartFormDataParser.php
tests/MultipartFormDataParserTest.php

Fix Fatal error: Exception 'RuntimeException' with message 'Unable to read stream contents' on run MultipartFormDataParserTest::testParse()
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes

Fix MultipartFormDataParser construction errors

---

config/web.php

| Is bugfix?    | 
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | 

remove duplicate config key "assetManager"

---

src/Middleware/IpFilter.php
src/Middleware/Redirect.php

| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no tests :(
| Fixed issues  | #68

Fix #68: Implement redirect

---

composer.json

| Tests pass?   | ❌
| Fixed issues  | ❌

Add yiisoft/factory dev dependency

---

src/ErrorHandler/HtmlRenderer.php
src/ErrorHandler/JsonRenderer.php
src/ErrorHandler/PlainTextRenderer.php
src/ErrorHandler/XmlRenderer.php
src/ErrorHandler/templates/callStackItem.php
src/ErrorHandler/templates/exception.php
src/ErrorHandler/templates/previousException.php
src/Info.php

| Tests pass?   | -
| Fixed issues  | #78

Add rough port of HTML error view

---

config/web.php

Remove 'app' in config

---

composer.json
src/Middleware/Csrf.php

| Tests pass?   | -
| Fixed issues  | #77

Implement CSRF middleware

---

.travis.yml
composer.json
phpunit.xml.dist
src/Cookie.php
tests/CookieTest.php
tests/bootstrap.php

Fix travis

---

src/Middleware/Redirect.php
tests/Middleware/RedirectTest.php

Redirect middleware unit tests

---

src/Flash.php
src/FlashInterface.php
tests/Flash/FlashTest.php

Adjusted public API of Flash

---

src/ServerRequestFactory.php

Fix #121 removed unnecessary ucwords header name

---

src/User/User.php

make code easier to read (or understand)

---

tests/Middleware/ActionCallerTest.php
tests/Middleware/TagRequestTest.php
tests/Middleware/WebActionsCallerTest.php

WebActionsCaller, ActionCaller and TagRequest tests

---

tests/Emitter/SapiEmitterTest.php

Test for SapiEmitter

---

composer.json
src/Middleware/ErrorCatcher.php
tests/Middleware/ErrorCatcherTest.php
tests/Middleware/Mock/MockRequestHandler.php
tests/Middleware/Mock/MockThrowableRenderer.php

ErrorCatcher with custom renderers #145

---

src/User/User.php

Fixed bug receiving identity

---

src/Emitter/SapiEmitter.php
tests/Emitter/SapiEmitterTest.php

The Emitter now emit body in parts

---

src/Emitter/SapiEmitter.php

| Fixed PR  | https://github.com/yiisoft/yii-web/pull/167

SapiEmitter::emitBody() dupliicated code fix

---

tests/Middleware/ActionCallerTest.php
tests/Middleware/CallbackTest.php
tests/Middleware/ChainTest.php
tests/Middleware/CsrfTest.php
tests/Middleware/IpFilterTest.php
tests/Middleware/RedirectTest.php
tests/Middleware/TagRequestTest.php
tests/Middleware/WebActionsCallerTest.php
tests/MiddlewareDispatcherTest.php
tests/NotFoundHandlerTest.php
tests/Session/SessionMiddlewareTest.php

Add return type declaration to tests

---

tests/Middleware/IpFilterTest.php
tests/Middleware/WebActionsCallerTest.php
tests/MiddlewareDispatcherTest.php
tests/Session/SessionMiddlewareTest.php

https://travis-ci.org/yiisoft/yii-web/builds/620956682?utm_source=github_status&utm_medium=notification

IpFilterTest::setUp() return type fix

---

src/User/User.php

User simplify code

---

src/Exception/BadUriPrefixException.php
src/Middleware/SubFolderMiddleware.php
tests/Middleware/RedirectTest.php

| Fixed issues  | https://github.com/yiisoft/yii-demo/issues/11 https://github.com/yiisoft/yii-demo/pull/34
Added SubfolderMiddleware which supports routing when webroot is not the same folder as public

Subfolder support

---

src/User/User.php

| Breaks BC?    |❌
Fixed method `User::logout` its now actually ending user session

fixed user logout

---

src/User/User.php
tests/Middleware/RedirectTest.php

| Fixed issues  | bug on User::can method replaced illegal method name of interface

Bugfix user permission

---

src/ErrorHandler/templates/callStackItem.php
src/ErrorHandler/templates/error.php
src/ErrorHandler/templates/exception.php
tests/Emitter/HTTPFunctionsTest.php
tests/Emitter/SapiEmitterTest.php

fix unit tests running in separate process

---

README.md

Update PHP version in  README

---

src/Config/EventConfigurator.php

Add type check for event listeners

---

src/User/AutoLoginMiddleware.php

| Fixed issues  | #251
Found this during working on:
https://github.com/yiisoft/yii-web/pull/252

Use returned response object with added header in AutologinMiddleware

---

tests/User/AutoLoginMiddlewareTest.php

| Is bugfix?   |  ❌
| New feature? |  ❌
| Breaks BC?    |  ❌
| Tests pass?   | ❌
| Fixed issues  | #251

Additional test cases for setting cookie header after login and logout

---

src/Config/EventConfigurator.php
src/Cookie.php
src/CookieCollection.php
src/ErrorHandler/ErrorException.php
src/ServerRequestFactory.php
src/User/User.php

Fix static analysis issues

---

config/params.php
config/web.php

Adjust config.

---

tests/User/AutoLoginMiddlewareTest.php

Fix deprecation

---

src/MiddlewareDispatcher.php

fix legacy middleware double pass

---

src/ErrorHandler/ErrorHandler.php
src/ErrorHandler/HtmlRenderer.php

| Fixed issues  | https://github.com/yiisoft/yii-web/issues/302, not rendering fallback error, not rendering server info

Fix error handler

---

src/User/UserAuth.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
`Yiisoft\Auth\AuthInterface` implementation for the `User` class to use it in `Auth` middleware.
I'm not sure on naming and having default `authUrl` predefined.
P.S. Will add tests as soon you give the green light.

Added AuthInterface implementation for the User.

---

src/User/UserAuth.php
tests/Mock/MockIdentityRepository.php
tests/User/UserAuthTest.php

| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any
Applied fix to use correct interface after changing to `yiisoft/auth` stable, made the class immutable and added tests.
Also fixed previously failing tests.

Yiisoft auth fix

---

src/ErrorHandler/HtmlRenderer.php

Fix PHP 8 ob_implicit_flush() call

---

src/ErrorHandler/ErrorHandler.php

| Fixed issues  | 
It's needed for #309

Added handy setters to ErrorHandler

---

src/Application.php
tests/ApplicationTest.php

| Is bugfix?    | ✔️/❌
| New feature?  | ✔️/❌
| Breaks BC?    | ✔️/❌
| Fixed issues  | #309

Moved out error handler from application

---

.github/workflows/build.yml
.github/workflows/static.yml
README.md
config/params.php
config/web.php

Enhacements

---

composer.json
config/params.php
config/web.php

Need merge after release `yiisoft/aliases:1.1.0`

Prepare to yiisoft/aliases:^1.1.0

---

.github/workflows/bc.yml_
.github/workflows/build.yml
.github/workflows/mutation.yml
.scrutinizer.yml
README.md
composer.json
infection.json.dist

Update dev dependencies, pipelines and scrutinizer.

---

src/SapiEmitter.php

| Fixed issues  | 
https://github.com/yiisoft/docs/blob/master/010-code-style.md#strings

Fixed code style src/SapiEmitter.php

---

src/SapiEmitter.php

Remove SapiEmitter return

---

composer.json
psalm.xml
src/ServerRequestFactory.php

Fix Psalm issues for errorLevel 4

---

src/Middleware/ForceSecureConnection.php
src/Middleware/HttpCache.php
src/Middleware/Redirect.php
tests/Middleware/HttpCacheTest.php
tests/Middleware/RedirectTest.php

Make middleware immutable

---

src/ServerRequestFactory.php

This PR fixes the following:
1. Prevents duplication of the `Host` header in the request.
2. Adds parsing of headers prefixed with `REDIRECT_` and `CONTENT_`.
3. Removes empty headers in the request, this is especially true for `Content-Length` and `Content-Type`.
4. Makes the first letter of each word in the header name uppercase when parsing, like the `getallheaders()` function.

Fix headers parsing to ServerRequestFactory

---

src/ServerRequestFactory.php
tests/ServerRequestFactoryTest.php

Return use of empty value to headers, add test for headers parsing

---

src/Middleware/TrustedHostsNetworkResolver.php
tests/Middleware/IpFilterTest.php

see https://github.com/yiisoft/validator/pull/134

Adopt to new yiisoft/validator

---

composer.json
src/Application.php
tests/ApplicationTest.php
tests/Mock/MockEventDispatcher.php

Fix test, add more tests & minor changes
